### ISSUE TITLE
Exporting `usdt::Error` can lead to compatibility issues for downstream crates

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/slog-dtrace#7]
In the probe registration process, we publicly export the `usdt::Error` type here:

https://github.com/oxidecomputer/slog-dtrace/blob/92241abea744db58b8e48eb982bf04330a501a4f/src/lib.rs#L137

That can lead to compatibility problems for consumers that depend on both `usdt` itself and also `slog-dtrace`. Suppose that consumer bumps the direct `usdt` rev in an incompatible way, and that they also make explicit reference to the `usdt::Error` type in some places. For example:

```rust

/// Some error type which explicitly refers to USDT's error type.
#[derive(thiserror::Error)]
pub enum MyError {
    Usdt(#[from] usdt::Error),
    /// Other variants
}

/// Attempt to use `slog_dtrace`
let (drain, registration) = slog_dtrace::with_drain(some_drain);
match registration {
    slog_dtrace::ProbeRegistration::Success => {},
    slog_dtrace::ProbeRegistration::Failed(err) => return Err(MyError::Usdt(err)),
}
```

That match arm converting the re-exported error type to `MyError::Usdt` will fail to compile, since those refer to two different and incompatible versions of the `usdt::Error` type.

As a side note, there's a legitimate question as to whether `usdt` should even _have_ a meaningful error type in its public interface. There is extremely little that one could do programmatically with it. If it's a failure to parse some provider definition in D; or a failure to `ioctl(2)` the DOF to the kernel, the options are basically the same:

1. Ignore it
2. Print it
3. Panic

In particular, one can't _recover_ from the error in any real way.

**Comment by jclulow** [comment]
I think it still helps for debugging to report _why_ the error occurred; e.g., what was the **ioctl()** and what was the **errno** value, if it's a parse failure what _was_ the failure, etc.

**Comment by bnaecker** [comment]
Agreed, I think the idea would be to export the information but not as that type. For example, wrapping things in an `anyhow::Error` or simply a `String`. So you could still learn why things failed and make changes, but not necessarily programmatically.

**Comment by jclulow** [comment]
Yeah I think it would be fine if you had `slog_dtrace::ProbeRegistration::Failed(String)` instead.
